background_opacity 0.6
dynamic_background_opacity yes
allow_remote_control yes
listen_on unix:/tmp/kitty-{kitty_pid}
include color_scheme.conf

cursor_trail 10
cursor_trail_start_threshold 0
cursor_trail_decay 0.05 0.2
